
#spring:
#  r2bdc:
#    url: r2dbc:mysql://10.167.150.29:3306/open_api?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
#    username: data_usr
#    password: GHYwlh123adzx
#    name: r2dbc
#    pool:
#      validation-query: SELECT 1
#      enabled: true

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG